/* ==========================================================================
   maps-data.js — Chen Family Vacation Aug 2026
   Budapest → Hévíz → Moravske Toplice → Bled → Budapest
   ========================================================================== */
window.MAPDATA = {

  /* ============================ Base 1 — Hévíz ============================ */
  base1: {
    hotel: { name: "Hévíz apartment (town center)", lat: 46.7907, lng: 17.1886 },
    pois: [
      { name:"Lake Hévíz — Thermal Bath", category:"pool", lat:46.7934, lng:17.1872, drive_min:3,
        desc:"Europe's largest thermal lake — warm water year-round, shallow roped zone for kids, unique black-mineral water.",
        hours:"May–Sep: Mon–Sat 09:00–17:30 · Sun to 13:30 · verify before visit" },
      { name:"Festetics Palace & Gardens (Keszthely)", category:"castle", lat:46.7737, lng:17.2446, drive_min:10,
        desc:"Baroque palace with ornate Helikon Library and lovely gardens — 10 min drive, combined family ticket available.",
        hours:"Tue–Sun 10:00–18:00 (Aug)" },
      { name:"Balaton South Shore Beach (Siófok)", category:"nature", lat:46.9060, lng:18.0526, drive_min:50,
        desc:"Hungary's warm shallow lake — south shore stays ankle-deep far out, perfect for Aviv (5). Pedal boats, ice cream.",
        hours:"Free access · lifeguards Jul–Aug" },
      { name:"Tihany Peninsula & Echo Hill", category:"scenic", lat:46.9125, lng:17.8880, drive_min:55,
        desc:"Dramatic volcanic headland on Lake Balaton — lavender fields, famous echo point, Benedictine abbey with panoramic views.",
        hours:"Free access · abbey daily 09:00–17:00" },
      { name:"Thermal Restaurant Zöldfa", category:"restaurant", lat:46.7910, lng:17.1898, drive_min:1,
        desc:"Popular family restaurant in Hévíz center — goulash, schnitzel, kids' menu, shaded terrace.",
        hours:"Daily 11:30–22:00" },
      { name:"Borcsa Restaurant (Hévíz)", category:"restaurant", lat:46.7895, lng:17.1905, drive_min:2,
        desc:"Good-value Hungarian home cooking; half portions for kids, friendly staff.",
        hours:"Daily 12:00–21:00" },
      { name:"Spar Supermarket (Hévíz)", category:"supermarket", lat:46.7920, lng:17.1930, drive_min:3, sunday:"limited",
        desc:"Central supermarket — full range, bakery, deli counter.",
        hours:"Mon–Fri 07:00–20:00 · Sat 07:00–18:00 · Sun 08:00–12:00" },
      { name:"Aldi Hévíz", category:"supermarket", lat:46.7870, lng:17.1960, drive_min:5, sunday:"closed",
        desc:"Budget supermarket with good fresh produce and local dairy.",
        hours:"Mon–Sat 08:00–20:00 · Sun closed" },
    ],
  },

  /* ============================ Base 2 — Moravske Toplice ============================ */
  base2: {
    hotel: { name: "Terme 3000 area apartment (Moravske Toplice)", lat: 46.6850, lng: 16.2215 },
    pois: [
      { name:"Terme 3000 — Thermal Water Park", category:"pool", lat:46.6855, lng:16.2228, drive_min:2,
        desc:"22 indoor/outdoor thermal pools incl. black mineral water, slides complex, shallow kids' zone. Main thermal-park day of the trip.",
        hours:"Daily 09:00–21:00 · outdoor pools to 20:00" },
      { name:"Schlossbergrutsche — The Slide (Graz)", category:"attraction", lat:47.0697, lng:15.4380, drive_min:88,
        desc:"64m underground slide inside Schlossberg hill — world's tallest indoor slide. Must-do for Noga & Inbar. Combine with clock tower views (~€6.50 adult, ~€4 child).",
        hours:"Daily 10:00–19:00" },
      { name:"Schlossberg Clock Tower & Views (Graz)", category:"scenic", lat:47.0719, lng:15.4384, drive_min:87,
        desc:"Icon of Graz — funicular or free climb, stunning panoramic rooftop views. Walk the hill after the slide.",
        hours:"Funicular daily 09:00–23:00 (runs on demand)" },
      { name:"Vinarium Tower (Lendava)", category:"scenic", lat:46.5718, lng:16.4538, drive_min:28,
        desc:"53m wine-region tower — elevator or 240 steps, see 4 countries on a clear day. ~€7 adult, ~€5 child. Kids love the elevator.",
        hours:"Tue–Sun 10:00–18:00 · Mon closed" },
      { name:"Ptuj — Oldest Slovenian Town", category:"castle", lat:46.4199, lng:15.8697, drive_min:35,
        desc:"Fairy-tale medieval hilltop castle and old town. Extremely photogenic, walkable, kid-friendly. Free to wander.",
        hours:"Castle museum daily 09:00–18:00 (Aug)" },
      { name:"Gostilna Rajh (Moravske Toplice)", category:"restaurant", lat:46.6834, lng:16.2165, drive_min:4,
        desc:"Best local inn near Terme 3000 — traditional Prekmurje cuisine (bograč stew, gibanica), family tables.",
        hours:"Daily 11:00–22:00" },
      { name:"Gostilna Štruc (Moravske Toplice)", category:"restaurant", lat:46.6820, lng:16.2190, drive_min:3,
        desc:"Casual Slovenian country kitchen, affordable lunches, chicken schnitzel the kids will love.",
        hours:"Mon–Sat 10:00–20:00 · Sun 11:00–16:00" },
      { name:"Mercator Moravske Toplice", category:"supermarket", lat:46.6864, lng:16.2201, drive_min:2, sunday:"limited",
        desc:"Main supermarket in the village — full range, good deli and bakery.",
        hours:"Mon–Fri 07:00–20:00 · Sat 07:00–15:00 · Sun 08:00–12:00" },
      { name:"Spar Lendava", category:"supermarket", lat:46.5685, lng:16.4525, drive_min:30, sunday:"closed",
        desc:"Larger supermarket in Lendava — good pit-stop combined with Vinarium Tower visit.",
        hours:"Mon–Fri 07:00–20:00 · Sat 07:00–15:00 · Sun closed" },
    ],
  },

  /* ============================ Base 3 — Bled ============================ */
  base3: {
    hotel: { name: "Bled apartment (Mlino / lakeside area)", lat: 46.3635, lng: 14.0984 },
    pois: [
      { name:"Bled Island — Pletna Boat", category:"attraction", lat:46.3685, lng:14.0927, drive_min:3,
        desc:"Row to the iconic island church on a traditional pletna flat-boat. Cash only (€20 adult · €10 child 4–12 · Aviv ~€10). Ring the wishing bell at the top.",
        hours:"Daily 08:00–18:00 (Aug)" },
      { name:"Bled Castle (Blejski Grad)", category:"castle", lat:46.3750, lng:14.1009, drive_min:5,
        desc:"11th-century clifftop castle with the best lake view of the trip — museum, printing press demo, and a wine cellar. Worth the climb.",
        hours:"Daily 08:00–20:00 (Aug)" },
      { name:"Vintgar Gorge", category:"nature", lat:46.4040, lng:14.0810, drive_min:12,
        desc:"1.6km boardwalk through a dramatic emerald gorge. Go early (before 09:30) to beat crowds. Aviv needs hand-holding on narrow sections.",
        hours:"Daily 08:00–19:00 (Jul–Aug) · last entry 18:00" },
      { name:"Straža Bled — Summer Toboggan", category:"attraction", lat:46.3565, lng:14.1089, drive_min:4,
        desc:"Chairlift up + toboggan run down. Aviv (5) rides tandem with an adult — Noga & Inbar can solo. 3-ride ticket best value (~€14 adult, ~€11 child).",
        hours:"Daily 10:00–19:00 (Jul–Aug) · weather-dependent" },
      { name:"Lake Bohinj & Vogel Cable Car", category:"nature", lat:46.2851, lng:13.8878, drive_min:30,
        desc:"Quieter glacier lake in Triglav National Park — turquoise water, mountain backdrop, wild swim. Vogel cable car to 1535m for big Alpine views (€33 adult · €16 child 6–14).",
        hours:"Cable car daily 08:00–18:00 (Jul–Aug)" },
      { name:"Wörthersee Beach + Minimundus (Klagenfurt)", category:"attraction", lat:46.6237, lng:14.3128, drive_min:75,
        desc:"Austria day — warm Alpine lake (26°C) swim then Minimundus miniature world (~€21 adult · €11 child · Aviv free). Both on the same Klagenfurt lakeshore.",
        hours:"Minimundus: daily 09:00–20:00 (Thu–Mon) · to 22:00 (Tue–Wed) Jul–Aug" },
      { name:"Postojna Cave", category:"attraction", lat:45.7831, lng:14.2054, drive_min:70,
        desc:"Electric train into Europe's largest cave — 1.5h tour, cool 10°C (bring a fleece). Book online. Aviv €1 ticket! Adult €28.80 · child €19.50.",
        hours:"Tours on the hour 09:00–18:00 (Aug) · must book online" },
      { name:"Ljubljana Old Town", category:"scenic", lat:46.0514, lng:14.5066, drive_min:55,
        desc:"Slovenia's lively pedestrian capital — dragon bridge, castle funicular, riverside cafés and ice cream. Good half-day or rainy-day option.",
        hours:"Free · Castle 09:00–21:00" },
      { name:"Kremšnita Café (Parkhotel Bled)", category:"restaurant", lat:46.3672, lng:14.1098, drive_min:5,
        desc:"THE Bled cream cake (kremšnita) — vanilla custard + whipped cream in puff pastry. A trip non-negotiable. ~€5 each.",
        hours:"Daily 07:30–21:00" },
      { name:"Gostilna Pri Planincu", category:"restaurant", lat:46.3688, lng:14.1075, drive_min:4,
        desc:"Traditional Slovenian inn near the lake — hearty mains, local wine, good kids' menu, fair prices for Bled.",
        hours:"Daily 10:00–22:00" },
      { name:"Finefood Restaurant (Bled)", category:"restaurant", lat:46.3668, lng:14.1062, drive_min:3,
        desc:"Reliable family restaurant — pizza, pasta and Slovenian mains, friendly for a quick lunch.",
        hours:"Daily 11:00–22:00" },
      { name:"Mercator Bled", category:"supermarket", lat:46.3650, lng:14.1050, drive_min:3, sunday:"limited",
        desc:"Main supermarket in Bled — full range including prepared foods for apartment meals.",
        hours:"Mon–Sat 07:00–21:00 · Sun 08:00–20:00" },
      { name:"Interspar Lesce (near Bled)", category:"supermarket", lat:46.3590, lng:14.1700, drive_min:10, sunday:"closed",
        desc:"Larger hypermarket 10 min away — best for big shopping runs.",
        hours:"Mon–Sat 07:00–21:00 · Sun closed" },
    ],
  },

  /* ============================ Base 4 — Budapest ============================ */
  base4: {
    hotel: { name: "Budapest apartment (District V–VII)", lat: 47.4979, lng: 19.0402 },
    pois: [
      { name:"Aquaworld Water Park", category:"pool", lat:47.5694, lng:19.1090, drive_min:20,
        desc:"Budapest's biggest water park — 11 slides, wave pool, lazy river, indoor + outdoor. ~€33 adult · €20 child · Aviv free. Book online to guarantee entry.",
        hours:"Daily 07:00–21:00" },
      { name:"Széchenyi Thermal Baths", category:"pool", lat:47.5187, lng:19.0813, drive_min:18,
        desc:"Iconic yellow palace baths in City Park — outdoor thermal pools, steam rooms. A Budapest icon. Bring swimwear + flip-flops.",
        hours:"Daily 06:00–22:00 (pools to 21:00)" },
      { name:"Palatinus Water Park (Margaret Island)", category:"pool", lat:47.5296, lng:19.0476, drive_min:15,
        desc:"Big outdoor water park on the island — wave pool, slides, family pools. Lower price than Aquaworld, easy walk from the island gardens.",
        hours:"Daily 09:00–19:00 (Jun–Aug)" },
      { name:"Buda Castle & Fisherman's Bastion", category:"castle", lat:47.4963, lng:19.0398, drive_min:10,
        desc:"The neo-Gothic fairy-tale bastion with the best Danube + parliament panorama. Funicular from Chain Bridge or walk up. Terrace access free.",
        hours:"Bastion daily 09:00–23:00 · towers €3 · Castle museum 10:00–18:00" },
      { name:"Hungarian Parliament — Danube View", category:"scenic", lat:47.5072, lng:19.0455, drive_min:12,
        desc:"Europe's third largest parliament — best viewed from the Buda bank at dusk. Guided tours inside (book in advance).",
        hours:"Tours daily: English 10:00, 12:00, 14:00" },
      { name:"Heroes' Square & City Park", category:"park", lat:47.5140, lng:19.0787, drive_min:18,
        desc:"Grand millennial monument + City Park with Vajdahunyad Castle, rowboat lake, and the Széchenyi baths — a full half-day.",
        hours:"Free access · park always open" },
      { name:"Margaret Island (Margitsziget)", category:"park", lat:47.5296, lng:19.0477, drive_min:14,
        desc:"3km car-free island — musical fountain, playground, rose garden, and the Palatinus water park. Aviv will love the fountain show (hourly in summer).",
        hours:"Free access · always open" },
      { name:"Great Market Hall (Nagyvásárcsarnok)", category:"shopping", lat:47.4882, lng:19.0580, drive_min:10,
        desc:"Budapest's biggest covered market — lángos on the ground floor, paprika and embroidery souvenirs upstairs. Ideal lunch stop.",
        hours:"Mon 06:00–17:00 · Tue–Fri 06:00–18:00 · Sat 06:00–15:00 · Sun closed" },
      { name:"Hungarikum Bisztró", category:"restaurant", lat:47.4961, lng:19.0535, drive_min:8,
        desc:"Authentic Hungarian bistro — excellent goulash, chicken paprikash, and lángos. Family-friendly, honest prices.",
        hours:"Daily 12:00–23:00" },
      { name:"Déryné Bisztró (Buda)", category:"restaurant", lat:47.4998, lng:19.0359, drive_min:7,
        desc:"Charming Buda bistro with a garden — Hungarian comfort food, good kids' menu, calmer atmosphere than Pest.",
        hours:"Daily 10:00–23:00" },
      { name:"Rosenstein Restaurant", category:"restaurant", lat:47.5043, lng:19.0784, drive_min:15,
        desc:"Budapest institution — Hungarian Jewish cuisine, legendary stuffed cabbage and cherry strudel. A special dinner for the last night.",
        hours:"Mon–Sat 12:00–23:00 · Sun 12:00–16:00" },
      { name:"Spar Supermarket (V. kerület)", category:"supermarket", lat:47.4972, lng:19.0524, drive_min:5, sunday:"limited",
        desc:"Central Pest Spar — convenient for apartment groceries.",
        hours:"Mon–Sat 07:00–21:00 · Sun 08:00–17:00" },
      { name:"Aldi Budapest (VIII. kerület)", category:"supermarket", lat:47.4941, lng:19.0740, drive_min:12, sunday:"closed",
        desc:"Budget supermarket — best for bulk snacks and day-trip supplies.",
        hours:"Mon–Sat 08:00–21:00 · Sun closed" },
    ],
  },

};
